###### VARIABLES YOU SHOULD CONFIGURE FOR YOUR DEPLOYEMNT
###### OR PASS as "-e" args to ansible-playbook command

## guid is the deployment unique identifier, it will be appended to all tags,
## files and anything that identifies this environment from another "just like it"
guid: defaultguid

# Project Tag for all generated resources
project_tag: "{{ env_type }}-{{ guid }}"

# Is this running from Red Hat Ansible Tower
tower_run: false

### Where to get Red Hat Repos. Only 'satellite' is supported for RHEL 8
repo_method: satellite

# satellite_url: satellite.example.com
# satellite_org: Sat_org_name
# satellite_activationkey: "rhel7basic"

# If you are doing RHEL 8, you must set these values
# satellite_url
# satellite_key
# satellite_cert

# Do you want to run a full yum update
update_packages: true

# Packages to install for RHEL 8
common_packages_el8:
- python3
- unzip
- bash-completion
- tmux
- bind-utils
- wget
- nano
- git
- vim-enhanced
- httpd-tools
- openldap-clients
- podman
- tree

cloud_tags:
  env_type: "{{ env_type }}"
  guid: "{{ guid }}"
  course_name: "{{ course_name | d('unknown') }}"
  platform: "{{ platform | d('unknown') }}"

studentvm_defaults:
  studentvm_roles:
  - studentvm-base
  - studentvm-user
  - studentvm-ftl
# - studentvm-ocp4

  install_opentlc_integration: true
#  install_ipa_client: false

  # Install a user id 'lab-user'.
  # If no student_password is provided a randomly generated password will be used
  install_student_user: false
  student_name: "lab-user"
  student_password: ""

  ### If you want a Key Pair name created and injected into the hosts,
  # set `set_env_authorized_key` to true and set the keyname in `env_authorized_key`
  # you can use the key used to create the environment or use your own self generated key
  # if you set "use_own_key" to false your PRIVATE key will be copied to the bastion. (This is {{key_name}})

  use_own_key: true
  set_env_authorized_key: true
  env_authorized_key: "{{guid}}key"
  key_name: "student_key"
  ansible_ssh_private_key_file: ~/.ssh/{{key_name}}.pem

