---
- name: Step 000 Pre Infrastructure
  hosts:
  - localhost
  connection: local
  become: false
  gather_facts: false
  tags:
  - step001
  - pre_infrastructure
  tasks:
  - name: Set up studentvm combined dictionary
    set_fact:
      studentvm: >-
        {{ studentvm_defaults
        | combine( studentvm_osp_defaults | default( {} ),
                   studentvm_ec2_defaults | default( {} ),
                   studentvm_vars         | default( {} ),
                   studentvm_secrets      | default( {} ), recursive=true )
        }}
  - name: Print combined config variables
    debug:
      var: studentvm
      verbosity: 2

  - name: Set legacy variables for other roles
    set_fact:
      # infra-osp-* roles
      student_name: "{{ studentvm.student_name }}"
      # set_env_authorized_key role
      env_authorized_key: "{{ studentvm.env_authorized_key }}"
