---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
  - debug:
      msg: "Software tasks started"

- name: Set up StudentVM
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
  - name: Run Student VM roles
    when:
    - studentvm.studentvm_roles | d("") | length > 0
    block:
    - name: Run Student VM Role
      include_role:
        name: "{{ item }}"
      loop: "{{ studentvm.studentvm_roles }}"

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
  - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
