---
- name: Set up studentvm_ftl combined dictionary
  set_fact:
    studentvm_ftl: >-
      {{ studentvm_ftl_defaults
       | combine(studentvm_ftl_vars    | default( {} ),
                 studentvm_ftl_secrets | default( {}), recursive=true )
      }}
- name: Print combined role variables
  debug:
    var: studentvm_ftl
    verbosity: 2

- name: Call FTL Injector
  include_role:
    name: ftl-injector
  vars:
    student_login: "{{ studentvm_ftl.student_name }}"
    use_python3: true

- name: Ensure system Python3 has selinux library installed
  pip:
    state: present
    executable: /usr/bin/pip3
    name: selinux
    version: 0.2.1
