---
- name: Set up studentvm_base combined dictionary
  set_fact:
    studentvm_base: >-
      {{ studentvm_base_defaults
       | combine(studentvm_base_vars    | default( {} ),
                 studentvm_base_secrets | default( {}), recursive=true )
      }}
- name: Print combined role variables
  debug:
    var: studentvm_base
    verbosity: 2

- name: Copy the user's SSH private key
  become: true
  copy:
    src: "~/.ssh/{{ key_name }}.pem"
    dest: "/root/.ssh/{{ key_name }}.pem"
    owner: root
    group: root
    mode: 0400
  when: not studentvm_base.use_own_key | bool

- name: Generate host .ssh/config Template
  become: no
  local_action: template src={{ role_path }}/templates/studentvm_ssh_config.j2 dest={{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}

- name: copy over host .ssh/config Template
  become: true
  copy:
    src: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: 0400

- name: Stat /etc/sysconfig/iptables
  stat:
    path: /etc/sysconfig/iptables
  register: statiptables
